### ISSUE TITLE
mapToGenome for the EPIC data

### ISSUE THREAD

**Issue by hcli0325** [kasperdanielhansen/minfi#102]
Hi! I am using the mapToGenome function to get genome annotation for my Illumina HumanMethylation EPIC data. Here is my code:
`myDataGenome<-mapToGenome(myDataSIBoth)`
and here is the returned message:
`Loading required package: IlluminaHumanMethylationEPICanno.ilmn10.hg19
Error in getAnnotationObject(object) : 
  cannot load annotation package IlluminaHumanMethylationEPICanno.ilmn10.hg19`
It seems to me that the " IlluminaHumanMethylationEPICanno.ilmn10.hg19" package has been updated to “ IlluminaHumanMethylationEPICanno.ilmn10b2.hg19”. So I guess maybe the released version of minfi did not include this update?
Thanks.

**Comment by kasperdanielhansen** [comment]
When you create your data objects in minfi they link to "current" annotations.  In this case "IlluminaHumanMethylationEPICanno.ilmn10.hg19" has (was) declared unsupported by Illumina, so we do not release this anymore.  The best thing is probably to recreate your objects using `read.meth.exp()`.  It is possible to do shortcuts by modifying the annotation slot, but that is for experts.

**Comment by kasperdanielhansen** [comment]
So in case I was not clear: you created your object using an old version of minfi and you're analyzing it using a newer version.
