### ISSUE TITLE
manifest file update in minfiEPIC

### ISSUE THREAD

**Issue by lxcfuji** [kasperdanielhansen/minfi#117]
I was told that 977 markers/sites of final content displayed in the previous version of the product manifest (MethylationEPIC_v-1-0_B2.bpm) have been removed, and the most updated version is v.1.0_B4. Is there way I can run minfi using the B4 file?
Thank you in advance

**Comment by kasperdanielhansen** [comment]
I assume you're closing this because you have solved it. We have B3 in Bioconductor; have they already released a B4? If so, I should make the annotation package.

**Comment by lxcfuji** [comment]
it looks like they were removed from manifest files that minfi pulled, although IlluminaHumanMethylationEPICmanifest.pdf (June 20, 2017) still said its based on B2, which confuses me a little. 
@kasperdanielhansen  Yes, they released B4 and I'm looking forward to your update of annotation package

**Comment by kasperdanielhansen** [comment]
Ok. Unfortunately I am heading on vacation in a few days.  Will see what I can do.

**Comment by lxcfuji** [comment]
@kasperdanielhansen Thank you so much!

**Comment by lydiarck** [comment]
Hi, I was wondering if there was an update to this, or an estimate of when you might have a chance. We're trying to decide about using a workaround or waiting to see if the B4 annotation is available. Thanks!

**Comment by kasperdanielhansen** [comment]
I forgot about it on my vacation.  I'll try to get it done tomorrow. Thanks for the gentle reminder.

**Comment by kasperdanielhansen** [comment]
Hmm, I get some network error when I try to connect to the CSV file linked to from `https://support.illumina.com/array/array_kits/infinium-methylationepic-beadchip-kit/downloads.html`; the link is `ftp://webdata2:webdata2@ussd-ftp.illumina.com/downloads/productfiles/methylationEPIC/MethylationEPIC_v-1-0_B4.csv`

**Comment by lydiarck** [comment]
I hated to bug you about it, so thanks.
I was able to download the file -- is there some way I could send it to you?

**Comment by kasperdanielhansen** [comment]
I have usually been able to download from that webpage without problems, so I'll try to connect to it from another location and see if I get it.  Otherwise I can arrange an upload location or you could share it using (say) Dropbox. But let me try a different location first - it's easier.

**Comment by kasperdanielhansen** [comment]
Ok, I managed to get it using a different machine to connect to the FTP server. Weird.

**Comment by diannahussmann** [comment]
Hi @kasperdanielhansen , 
I'm working with EPIC data, and I was wondering if you will be providing a new annotation package for the EPIC v1.0 B4 manifest file in the near future? 
Many thanks!

**Comment by mwsill** [comment]
Hi,

I just recently generated a package for the B4 manifest version.

https://github.com/mwsill/IlluminaHumanMethylationEPICmanifest

best M

**Comment by kasperdanielhansen** [comment]
I have forgot to update this issue.  The B4 package was released with the latest Bioconductor release but is not the default at the time of writing.  You can fix this by
```
library(minfiDataEPIC) # access to RGsetEPIC)
annotation(RGsetEPIC)["annotation"] = "ilm10b4.hg19"
```
At this point you need to install the annotation package for the rest to work
```
source("https://www.bioconductor.org/biocLite.R")
biocLite("IlluminaHumanMethylationEPICanno.ilm10b4.hg1")
```
and now everything should work:
```
gmSet = mapToGenome(preprocessRaw(RGsetEPIC))
```
