### ISSUE TITLE
getGenomicRatioSetFromGEO() fails

### ISSUE THREAD

**Issue by wvictor14** [kasperdanielhansen/minfi#118]
Hi, using R 3.4.1 and minfi 1.22.1  

`gset <- getGenomicRatioSetFromGEO("GSE73375")` produces this error:

> 
> https://ftp.ncbi.nlm.nih.gov/geo/series/GSE73nnn/GSE73375/matrix/
> OK
> Found 1 file(s)
> GSE73375_series_matrix.txt.gz
> trying URL 'https://ftp.ncbi.nlm.nih.gov/geo/series/GSE73nnn/GSE73375/matrix/GSE73375_series_matrix.txt.gz'
> Content type 'application/x-gzip' length 76067808 bytes (72.5 MB)
> downloaded 72.5 MB
> 
> File stored at: 
> C:\Users\vyuan\AppData\Local\Temp\RtmpsB4RgO/GPL13534.soft
> Loading required package: IlluminaHumanMethylation450kanno.ilmn12.hg19
> Error in .local(assays, ...) : 
>   unused argument (pData = list(title = c(1, 12, 14, 15, 16, 18, 29, 31, 32, 33, 17, 2, 3, 4, 34, 35, 36, 19, 20, 21, 11, 13, 28, 30, 5, 6, 7, 8, 9, 10, 22, 23, 24, 25, 26, 27), geo_accession = 1:36, status = c(1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1), submission_date = c(1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1), last_update_date = c(1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 
> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1), type = c(1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1), channel_count = c(1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1), source_name_ch1 = c(1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1), organism_ch1 = c(1, 1, 1, 1, 1, 1, 1, 
> In addition: Warning message:
> In read.table(file = file, header = header, sep = sep, quote = quote,  :
>   not all columns named in 'colClasses' exist

**Comment by MohamedRefaat92** [comment]
I'm dealing with the same error. Have you found a solution yet?

**Comment by kasperdanielhansen** [comment]
This is fixed in minfi version 1.25.1 which I just submitted to Bioconductor and updated on Github.  Since this is a bugfix I will backport this to the stable release of Bioconductor and release minfi 1.24.1 in the stable branch.
