### ISSUE TITLE
Error in read.metharray.exp() function 

### ISSUE THREAD

**Issue by alna** [kasperdanielhansen/minfi#123]
I'm trying to use minfi's  read.metharray.exp() function to read targets, sample sheet contains 9 samples of E and U groups and 6 samples from C group,totally 24 samples  but i get this error:
codes:
baseDir<-"C:/Nadia/mdata"
targets=read.metharray.sheet(baseDir)
RGSet=read.metharray.exp(targets=targets)

Error in xx$Quants[commonAddresses, "Mean"] : subscript out of bounds

**Comment by PeteHaitch** [comment]
This sort of question is better posted to https://support.bioconductor.org/. It really helps if you can include a minimal reproducible example. Please take a look at http://www.bioconductor.org/help/support/posting-guide/ which will help people trying to help you.
