### ISSUE TITLE
RGChannelSet change from eSet subclass to SummarizedExperiment subclass

### ISSUE THREAD

**Issue by Alanocallaghan** [kasperdanielhansen/minfi#125]
Hi, I note a discrepancy between the package documentation and the code, notably below RGChannelSet inherits from SummarizedExperiment:
https://github.com/kasperdanielhansen/minfi/blob/master/R/rgset.R#L3

Yet the documentation makes no reference to this class and in fact claims that RGChannelSet inherits from eSet (which used to be true).
https://github.com/kasperdanielhansen/minfi/blob/master/man/RGChannelSet-class.Rd#L125

I would note that changing the inheritance of established classes is a pretty unpleasant thing to do with published code in any case, but please update the documentation to reflect the changes made. Thanks.

**Comment by kasperdanielhansen** [comment]
Thanks, I'll fix this.

If it is any consolation, the change was not done lightly. This change is
paving the way for dramatically reducing the memory footprint of minfi; the
goal is to be able to run minfi in bounded memory with data loaded on
demand from disk.

Best,
Kasper

**Comment by kasperdanielhansen** [comment]
Btw, since the accessor functions still exists, you should be able to use existing code without changes. You can update old objects using updateObject().

**Comment by Alanocallaghan** [comment]
Sounds useful, especially for 850k data (currently only feasible for high memory machines).

The issues I was having relate to accessing and changing red/green or methylated/unmethylated values in MethylSet and RGChannelSet objects. eSet objects use `assayDataElement` while SummarizedExperiment uses the `assay` function. The change in inheritance broke my code, with some pretty confusing error messages, since the package docs didn't make the change clear

Thanks!
