### ISSUE TITLE
getGenomicRatioSetFromGEO broken v1.22.1

### ISSUE THREAD

**Issue by alexvnesta** [kasperdanielhansen/minfi#127]
mSetSq <- getGenomicRatioSetFromGEO(GSE = "GSE30654")
https://ftp.ncbi.nlm.nih.gov/geo/series/GSE30nnn/GSE30654/matrix/
OK
Found 3 file(s)
GSE30654-GPL13534_series_matrix.txt.gz
trying URL 'https://ftp.ncbi.nlm.nih.gov/geo/series/GSE30nnn/GSE30654/matrix/GSE30654-GPL13534_series_matrix.txt.gz'
Content type 'application/x-gzip' length 309790493 bytes (295.4 MB)

downloaded 295.4 MB

File stored at:
/var/folders/14/zdpg3tzd1kq5_w7qybng_49r0000gn/T//RtmpQ6jdxd/GPL13534.soft
GSE30654-GPL6947_series_matrix.txt.gz
trying URL 'https://ftp.ncbi.nlm.nih.gov/geo/series/GSE30nnn/GSE30654/matrix/GSE30654-GPL6947_series_matrix.txt.gz'
Content type 'application/x-gzip' length 38255623 bytes (36.5 MB)

downloaded 36.5 MB

File stored at:
/var/folders/14/zdpg3tzd1kq5_w7qybng_49r0000gn/T//RtmpQ6jdxd/GPL6947.soft
GSE30654-GPL8490_series_matrix.txt.gz
trying URL 'https://ftp.ncbi.nlm.nih.gov/geo/series/GSE30nnn/GSE30654/matrix/GSE30654-GPL8490_series_matrix.txt.gz'
Content type 'application/x-gzip' length 33013631 bytes (31.5 MB)

downloaded 31.5 MB

File stored at:
/var/folders/14/zdpg3tzd1kq5_w7qybng_49r0000gn/T//RtmpQ6jdxd/GPL8490.soft
Error in .local(assays, ...) :
unused argument (pData = list(title = c(16, 17, 7, 2, 3, 1, 13, 11, 12, 9, 10, 4, 5, 6, 8, 15, 14, 18, 19, 23, 25, 20, 21, 22, 24, 26, 27, 28, 29, 30, 31, 37, 36, 49, 48, 51, 50, 53, 52, 55, 54, 56, 58, 57, 39, 38, 40, 41, 43, 42, 45, 44, 47, 46, 60, 59, 33, 34, 32, 35, 63, 64, 66, 61, 62, 65, 67, 68, 69, 70, 71, 72, 90, 92, 80, 81, 75, 78, 79, 85, 82, 89, 88, 86, 87, 74, 83, 76, 77, 84, 91, 93, 73, 101, 132, 131, 147, 144, 145, 142, 146, 143, 103, 104, 114, 111, 112, 113, 110, 151, 150, 119, 116, 117, 118,
115, 123, 121, 122, 120, 109, 106, 107, 108, 105, 134, 133, 149, 148, 141, 139, 140, 137, 138, 153, 152, 130, 126, 127, 128, 124, 129, 125, 100, 98, 96, 99, 97, 136, 135, 95, 94, 102), geo_accession = 1:153, status = c(1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
In addition: Warning messages:
1: In read.table(file = file, header = header, sep = sep, quote = quote, :
not all columns named in 'colClasses' exist
2: In read.table(file = file, header = header, sep = sep, quote = quote, :
not all columns named in 'colClasses' exist
3: In read.table(file = file, header = header, sep = sep, quote = quote, :
not all columns named in 'colClasses' exist
4: In getGenomicRatioSetFromGEO(GSE = "GSE30654") :
More than one ExpressionSet found:
GSE30654-GPL13534_series_matrix.txt.gzGSE30654-GPL6947_series_matrix.txt.gzGSE30654-GPL8490_series_matrix.txt.gz
Using entry 1

**Comment by alexvnesta** [comment]
My apologies, It looks like the latest version 1.25.1 fixes this. I didn't realize I had to update bioconductor to get it.

**Comment by kasperdanielhansen** [comment]
NP.  Did you confirm it is fixed, or do you just think it might be fixed?

**Comment by alexvnesta** [comment]
looking into it now. Will update once verified.

**Comment by alexvnesta** [comment]
Updated to 1.25.1 All Fixed and verified with a quick data plot! Thank you for this package, and your prompt support!

Note: Latest release version is 1.24.0 which still has this issue. Had to install 1.25.1 from source via R CMD INSTALL. Also had to reinstall readr and tinyverse because of a weird install corruption issue. 


R version 3.4.3 (2017-11-30) -- "Kite-Eating Tree"
Copyright (C) 2017 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin15.6.0 (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> library("minfi", lib.loc="~/Library/R/3.4/library")
Loading required package: BiocGenerics
Loading required package: parallel

Attaching package: ‘BiocGenerics’

The following objects are masked from ‘package:parallel’:

    clusterApply, clusterApplyLB, clusterCall, clusterEvalQ,
    clusterExport, clusterMap, parApply, parCapply, parLapply,
    parLapplyLB, parRapply, parSapply, parSapplyLB

The following objects are masked from ‘package:stats’:

    IQR, mad, sd, var, xtabs

The following objects are masked from ‘package:base’:

    anyDuplicated, append, as.data.frame, cbind, colMeans, colnames,
    colSums, do.call, duplicated, eval, evalq, Filter, Find, get, grep,
    grepl, intersect, is.unsorted, lapply, lengths, Map, mapply, match,
    mget, order, paste, pmax, pmax.int, pmin, pmin.int, Position, rank,
    rbind, Reduce, rowMeans, rownames, rowSums, sapply, setdiff, sort,
    table, tapply, union, unique, unsplit, which, which.max, which.min

Loading required package: GenomicRanges
Loading required package: stats4
Loading required package: S4Vectors

Attaching package: ‘S4Vectors’

The following object is masked from ‘package:base’:

    expand.grid

Loading required package: IRanges
Loading required package: GenomeInfoDb
Loading required package: SummarizedExperiment
Loading required package: Biobase
Welcome to Bioconductor

    Vignettes contain introductory material; view with
    'browseVignettes()'. To cite Bioconductor, see
    'citation("Biobase")', and for packages 'citation("pkgname")'.

Loading required package: DelayedArray
Loading required package: matrixStats

Attaching package: ‘matrixStats’

The following objects are masked from ‘package:Biobase’:

    anyMissing, rowMedians


Attaching package: ‘DelayedArray’

The following objects are masked from ‘package:matrixStats’:

    colMaxs, colMins, colRanges, rowMaxs, rowMins, rowRanges

The following object is masked from ‘package:base’:

    apply

Loading required package: Biostrings
Loading required package: XVector

Attaching package: ‘Biostrings’

The following object is masked from ‘package:DelayedArray’:

    type

The following object is masked from ‘package:base’:

    strsplit

Loading required package: bumphunter
Loading required package: foreach
Loading required package: iterators
Loading required package: locfit
locfit 1.5-9.1 	 2013-03-22
Setting options('download.file.method.GEOquery'='auto')
Setting options('GEOquery.inmemory.gpl'=FALSE)
> mSetSq <- getGenomicRatioSetFromGEO(GSE = "GSE30654")
Found 3 file(s)
GSE30654-GPL13534_series_matrix.txt.gz
trying URL 'https://ftp.ncbi.nlm.nih.gov/geo/series/GSE30nnn/GSE30654/matrix/GSE30654-GPL13534_series_matrix.txt.gz'
Content type 'application/x-gzip' length 309790493 bytes (295.4 MB)
==================================================
downloaded 295.4 MB

Error in date_names_lang(date_names) : 
  cannot open file '~/Library/R/3.4/library/readr/R/sysdata.rdb': No such file or directory
> library(readr)
> library(minfi)
> install.packages("tidyverse")
Installing package into ‘/Users/Alex/Library/R/3.4/library’
(as ‘lib’ is unspecified)
also installing the dependencies ‘rematch’, ‘cellranger’, ‘callr’, ‘rmarkdown’, ‘selectr’, ‘dbplyr’, ‘forcats’, ‘haven’, ‘modelr’, ‘readxl’, ‘reprex’, ‘rvest’


  There is a binary version available but the source version is later:
       binary source needs_compilation
reprex  0.1.1  0.1.2             FALSE

trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.4/rematch_1.0.1.tgz'
Content type 'application/x-gzip' length 10990 bytes (10 KB)
==================================================
downloaded 10 KB

trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.4/cellranger_1.1.0.tgz'
Content type 'application/x-gzip' length 72965 bytes (71 KB)
==================================================
downloaded 71 KB

trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.4/callr_1.0.0.tgz'
Content type 'application/x-gzip' length 34740 bytes (33 KB)
==================================================
downloaded 33 KB

trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.4/rmarkdown_1.8.tgz'
Content type 'application/x-gzip' length 2227986 bytes (2.1 MB)
==================================================
downloaded 2.1 MB

trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.4/selectr_0.3-1.tgz'
Content type 'application/x-gzip' length 176065 bytes (171 KB)
==================================================
downloaded 171 KB

trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.4/dbplyr_1.2.0.tgz'
Content type 'application/x-gzip' length 316707 bytes (309 KB)
==================================================
downloaded 309 KB

trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.4/forcats_0.2.0.tgz'
Content type 'application/x-gzip' length 163820 bytes (159 KB)
==================================================
downloaded 159 KB

trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.4/haven_1.1.1.tgz'
Content type 'application/x-gzip' length 839173 bytes (819 KB)
==================================================
downloaded 819 KB

trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.4/modelr_0.1.1.tgz'
Content type 'application/x-gzip' length 133552 bytes (130 KB)
==================================================
downloaded 130 KB

trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.4/readxl_1.0.0.tgz'
Content type 'application/x-gzip' length 1405217 bytes (1.3 MB)
==================================================
downloaded 1.3 MB

trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.4/rvest_0.3.2.tgz'
Content type 'application/x-gzip' length 852813 bytes (832 KB)
==================================================
downloaded 832 KB

trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.4/tidyverse_1.2.1.tgz'
Content type 'application/x-gzip' length 77756 bytes (75 KB)
==================================================
downloaded 75 KB


The downloaded binary packages are in
	/var/folders/14/zdpg3tzd1kq5_w7qybng_49r0000gn/T//RtmpU16695/downloaded_packages
installing the source package ‘reprex’

trying URL 'https://cran.rstudio.com/src/contrib/reprex_0.1.2.tar.gz'
Content type 'application/x-gzip' length 22879 bytes (22 KB)
==================================================
downloaded 22 KB

* installing *source* package ‘reprex’ ...
** package ‘reprex’ successfully unpacked and MD5 sums checked
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
* DONE (reprex)

The downloaded source packages are in
	‘/private/var/folders/14/zdpg3tzd1kq5_w7qybng_49r0000gn/T/RtmpU16695/downloaded_packages’
> 
> install.packages("readr")
Error in install.packages : Updating loaded packages
> 

Restarting R session...

> install.packages("readr")
Installing package into ‘/Users/Alex/Library/R/3.4/library’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.4/readr_1.1.1.tgz'
Content type 'application/x-gzip' length 1967561 bytes (1.9 MB)
==================================================
downloaded 1.9 MB


The downloaded binary packages are in
	/var/folders/14/zdpg3tzd1kq5_w7qybng_49r0000gn/T//RtmpXDUcEv/downloaded_packages
> library(minfi)
Loading required package: BiocGenerics
Loading required package: parallel

Attaching package: ‘BiocGenerics’

The following objects are masked from ‘package:parallel’:

    clusterApply, clusterApplyLB, clusterCall, clusterEvalQ,
    clusterExport, clusterMap, parApply, parCapply, parLapply,
    parLapplyLB, parRapply, parSapply, parSapplyLB

The following objects are masked from ‘package:stats’:

    IQR, mad, sd, var, xtabs

The following objects are masked from ‘package:base’:

    anyDuplicated, append, as.data.frame, cbind, colMeans, colnames,
    colSums, do.call, duplicated, eval, evalq, Filter, Find, get, grep,
    grepl, intersect, is.unsorted, lapply, lengths, Map, mapply, match,
    mget, order, paste, pmax, pmax.int, pmin, pmin.int, Position, rank,
    rbind, Reduce, rowMeans, rownames, rowSums, sapply, setdiff, sort,
    table, tapply, union, unique, unsplit, which, which.max, which.min

Loading required package: GenomicRanges
Loading required package: stats4
Loading required package: S4Vectors

Attaching package: ‘S4Vectors’

The following object is masked from ‘package:base’:

    expand.grid

Loading required package: IRanges
Loading required package: GenomeInfoDb
Loading required package: SummarizedExperiment
Loading required package: Biobase
Welcome to Bioconductor

    Vignettes contain introductory material; view with
    'browseVignettes()'. To cite Bioconductor, see
    'citation("Biobase")', and for packages 'citation("pkgname")'.

Loading required package: DelayedArray
Loading required package: matrixStats

Attaching package: ‘matrixStats’

The following objects are masked from ‘package:Biobase’:

    anyMissing, rowMedians


Attaching package: ‘DelayedArray’

The following objects are masked from ‘package:matrixStats’:

    colMaxs, colMins, colRanges, rowMaxs, rowMins, rowRanges

The following object is masked from ‘package:base’:

    apply

Loading required package: Biostrings
Loading required package: XVector

Attaching package: ‘Biostrings’

The following object is masked from ‘package:DelayedArray’:

    type

The following object is masked from ‘package:base’:

    strsplit

Loading required package: bumphunter
Loading required package: foreach
Loading required package: iterators
Loading required package: locfit
locfit 1.5-9.1 	 2013-03-22
Setting options('download.file.method.GEOquery'='auto')
Setting options('GEOquery.inmemory.gpl'=FALSE)
> mSetSq <- getGenomicRatioSetFromGEO(GSE = "GSE30654")
Found 3 file(s)
GSE30654-GPL13534_series_matrix.txt.gz
trying URL 'https://ftp.ncbi.nlm.nih.gov/geo/series/GSE30nnn/GSE30654/matrix/GSE30654-GPL13534_series_matrix.txt.gz'
Content type 'application/x-gzip' length 309790493 bytes (295.4 MB)
==================================================
downloaded 295.4 MB

|=================================================================| 100%  722 MB
Parsed with column specification:
cols(
  .default = col_double(),
  ID_REF = col_character()
)
See spec(...) for full column specifications.
|=================================================================| 100%  722 MB
File stored at: 
/var/folders/14/zdpg3tzd1kq5_w7qybng_49r0000gn/T//RtmpXDUcEv/GPL13534.soft
|=================================================================| 100%  205 MB
|=================================================================| 100%  202 MB
GSE30654-GPL6947_series_matrix.txt.gz
trying URL 'https://ftp.ncbi.nlm.nih.gov/geo/series/GSE30nnn/GSE30654/matrix/GSE30654-GPL6947_series_matrix.txt.gz'
Content type 'application/x-gzip' length 38255623 bytes (36.5 MB)
==================================================
downloaded 36.5 MB

Parsed with column specification:
cols(
  .default = col_double(),
  ID_REF = col_character()
)
See spec(...) for full column specifications.
File stored at: 
/var/folders/14/zdpg3tzd1kq5_w7qybng_49r0000gn/T//RtmpXDUcEv/GPL6947.soft
GSE30654-GPL8490_series_matrix.txt.gz
trying URL 'https://ftp.ncbi.nlm.nih.gov/geo/series/GSE30nnn/GSE30654/matrix/GSE30654-GPL8490_series_matrix.txt.gz'
Content type 'application/x-gzip' length 33013631 bytes (31.5 MB)
==================================================
downloaded 31.5 MB

Parsed with column specification:
cols(
  .default = col_double(),
  ID_REF = col_character()
)
See spec(...) for full column specifications.
|=================================================================| 100%   77 MB
File stored at: 
/var/folders/14/zdpg3tzd1kq5_w7qybng_49r0000gn/T//RtmpXDUcEv/GPL8490.soft
Loading required package: IlluminaHumanMethylation450kanno.ilmn12.hg19
Warning message:
In getGenomicRatioSetFromGEO(GSE = "GSE30654") :
  More than one ExpressionSet found:
GSE30654-GPL13534_series_matrix.txt.gzGSE30654-GPL6947_series_matrix.txt.gzGSE30654-GPL8490_series_matrix.txt.gz
Using entry 1

> densityPlot(getBeta(mSetSq),
+             main="Normalized", legend=FALSE)

**Comment by kasperdanielhansen** [comment]
Thanks.  I was planning on backporting the fix to the stable branch, but I
had forgotten about it.  Thanks for closing the issue.
