### ISSUE TITLE
Error message when running preprocessFunnorm

### ISSUE THREAD

**Issue by Janitza** [kasperdanielhansen/minfi#14]
Hi, 

I'm running the preprocessFunnorm in my 450K Methylation analysis, but I receive this error message:

Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function 'getListElement' for signature '"CompressedSplitDataFrameList"'

Please, help!

Thank you!

**Comment by kasperdanielhansen** [comment]
Try to update all of Bioconductor with
   biocLite()
This is most likely a version mismatch.
