### ISSUE TITLE
could not find function "assayDataValidMembers" 

### ISSUE THREAD

**Issue by cgeisenberger** [kasperdanielhansen/minfi#40]
Hey there, 

I have recently started to write my first R package, mostly convenience functions around the minfi package to streamline my 450K idat processing. When I tried to call the minfi::read.450k function from within my package I got this error: 

Error in validMsg(NULL, assayDataValidMembers(assayData(object), c("Red",  : 
  could not find function "assayDataValidMembers" 

I think this is because the function is not imported into minfi. When I used library(Biobase) it worked fine.

All the best

Christoph

**Comment by kasperdanielhansen** [comment]
You're right.  I have fixed this in minfi on Github and will soon push to
Bioconductor.  You'll need minfi version 1.17.4.

**Comment by kasperdanielhansen** [comment]
Fixed in minfi 1.17.4. Closing.
