### ISSUE TITLE
Reading 850K

### ISSUE THREAD

**Issue by RaphaelRaphael** [kasperdanielhansen/minfi#43]
Do you plan to add a read.850K function in minfi ? I would be happy to propose one.

**Comment by kasperdanielhansen** [comment]
I am adding read.metharray right now which auto detects the array type.

Kasper

**Comment by RaphaelRaphael** [comment]
According to IMMUMINA tech support

we do not recommend analyzing Methylation450K and MethylationEPIC data together.

Will you still try to allow for kind of RGChannelSet objects to contain both 450K and 850K ?
It may raise question about matching the controls and the CG#.

**Comment by kasperdanielhansen** [comment]
We are putting the finishing touches on a normalization method which will
jointly normalize 450k and EPIC data.  Expect something from us soon.  This
method will just do the normalization.  You can then do analysis by
subsetting out the joint probes, or you could conceivably think about
imputation which is an open question.

We cannot extend the RGChannelSet to contain both data types, for technical
reasons.  Our normalization function will be something like

  normData = normalize(450 = rgset1, epic = rgset2)

and then you have normData$450k and normData$epic.  Then I think we'll
write a function like

  combineCommonProbes(450k, epic)

which will return a single object only containing the common probes.

Best,
Kasper

**Comment by RaphaelRaphael** [comment]
Thanks, I am impatient to see that !
