### ISSUE TITLE
Support gzipped files

### ISSUE THREAD

**Issue by kasperdanielhansen** [kasperdanielhansen/minfi#53]
There is support for gzipped files in illuminaio.  But currently, `read.metharray()` generates IDAT file name from `basename`.  This should be fixed to both generate with and without `.gz` and then search for files to decide which one to use.

**Comment by kasperdanielhansen** [comment]
Fixed in minfi 1.21.6.

cc to @ttriche who will be thrilled, but disappointed it took so long.

**Comment by ttriche** [comment]
better late than never!  Thanks much.


--t
