### ISSUE TITLE
add keepCN argument to preprocessFunnorm

### ISSUE THREAD

**Issue by mvaniterson** [kasperdanielhansen/minfi#57]
Hi Kasper, 

Would it be possible to add keepCN argument to preprocessFunnorm. Now by default both beta-values and CN-data is returned. I all most always use only the beta-values. This will reduce the size of the returned object, which is useful when normalizing a large number of samples.

Regards, 
Maarten

**Comment by kasperdanielhansen** [comment]
Supported in minfi 1.21.6.  Only took a year :(

**Comment by molepi** [comment]
Thanks for adding!
