### ISSUE TITLE
getBeta of RGChannelSet

### ISSUE THREAD

**Issue by Rory-R-Wilson** [kasperdanielhansen/minfi#82]
Dear developers,

It seems that the options of "offset" and "type" do not work when applying getBeta() directly to an RGChannelSet. No warning or error message is given, the betas are simply returned as calculated with no offset.
I am not sure if this is intentional or not - I could not directly determine this from the documentation. I just wanted to bring it to your attention.

Thank you,

Rory

**Comment by Jfortin1** [comment]
Hi Rory, 

Thanks for letting us know. Indeed the function for RGChannelSet should be

setMethod("getBeta", signature(object = "RGChannelSet"),
          function(object, ...) {
              object <- preprocessRaw(object)
              callGeneric(object, ...)
})

instead of 

setMethod("getBeta", signature(object = "RGChannelSet"),
          function(object, ...) {
              object <- preprocessRaw(object)
              callGeneric(object)
})

Going to fix that. Thanks!

**Comment by Rory-R-Wilson** [comment]
Okay! Thanks for your quick feedback.
Rory
