### ISSUE TITLE
controlStripPlot: bug when only one control sample

### ISSUE THREAD

**Issue by lcougnaud** [kasperdanielhansen/minfi#90]
I would like to use the `controlStripPlot` function for different control types.
There is only one feature present for one of the controls, which leads to the following error:
```
Error in UseMethod("melt", data) : 
  no applicable method for 'melt' applied to an object of class "c('double', 'numeric')"
```
because a numeric vector is extracted instead of a matrix in line:
`ctlWide <- log2(r[ctrlAddress, ])`
Replacing it by:
`ctlWide <- log2(r[ctrlAddress, , drop = FALSE])` solves the issue.
Would it be possible to include this fix in a new version? Or is there a more optimal code?
Thanks in advance!

**Comment by kasperdanielhansen** [comment]
Done in minfi 1.21.4.  Not sure this is worth backporting to the release
branch.  In the future you can edit files directly on Github and send the
edits as a "Pull request"; that makes it even easier for authors.

Thanks,
Kasper

**Comment by lcougnaud** [comment]
Thanks for your prompt response! This solves the issue.
Thanks also for all the work in the minfi package, this is a very useful tool for pre-processing and analysis of Illumina Infinium DNA methylation arrays.
