### ISSUE TITLE
updateObject RGChannelSetExtended

### ISSUE THREAD

**Issue by kkleinoros** [kasperdanielhansen/minfi#91]
Hi Kasper,
I have an rgset (EPIC) that I have created using minfi, I would like to run shinymethyl.  However, I can not load it into my devel version.  I saw your posts regarding updateObject, but I cant even load the object.
I do not have enough memory on devel version to build a new rgset (300 samples).
Any ideas?
Kathleen

**Comment by kasperdanielhansen** [comment]
You'll need to run this on a machine be with more RAM. We are working on algorithms using bounded memory, but it will take a while to get ready. My guess is that you created the object on a different machine. 

Best,
Kasper
(Sent from my phone.)
