### ISSUE TITLE
readmetharray force=TRUE

### ISSUE THREAD

**Issue by mwsill** [kasperdanielhansen/minfi#92]
Hi Kasper,

thanks for the hard work on the package. I am trying to read epic idats of different file sizes and I think you need to uncomment/delete line 58 in in read.meth.R to get the force=TRUE argument working?

Best,

Martin

**Comment by kasperdanielhansen** [comment]
You should only hit line 58 if you're trying to read data from different arrays (which is not supported and I don't intend to support it).  The situation with data from scans with different lengths of the same array is different; thats what we support.

Perhaps tell us more details or give two files as example.

**Comment by mwsill** [comment]
The file sizes are 13677911 instead of 13686979 and the number of probes are 1051943. Setting the annotation manually to "ilm10b2.hg19” works fine, however around 600 CpG probes are missing. The same probes seem to miss when reading the idat files with GenomeStudio. 
I sent you an email with more details and an idat pair.

**Comment by kasperdanielhansen** [comment]
Fixed in minfi 1.21.6.  It will take a few days before it appears on the Bioconductor servers.

**Comment by mwsill** [comment]
Thanks, I think the problematic probes are excluded by the new Illumina manifest released today.

**Comment by kasperdanielhansen** [comment]
No, we don't use the manifest when reading the files.  But the problem
should be solved in the devel version of minfi for example version 1.21.6
or higher.

**Comment by marencc** [comment]
I'd like to ask why would scans of different lengths happen?  As it seems to be a constant case if EPIC's arrays  [+Isn't it supposed to be all done uniformly by a machine? ]
>  The situation with data from scans with different lengths of the same array is different; thats what we support.
